In [ ]:
from sklearn.experimental import enable_iterative_imputer
import pandas as pd
import numpy as np
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,Normalizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
# import seaborn as nan

In [ ]:
df=pd.read_csv("dataset_divarR.csv")
df

,price,mantage,metrage,sal,otag,tabage,vshed_status,lat,long,tehdad_vahed,asansor,parking,anbari
0,1350000000,chitgar-shomali,90,1404.0,2.0,۸ از ۱۵,بازسازی نشده,35.724967,51.186593,8.0,آسانسور دارد,پارگینگ دارد,انباری دارد
1,89999998976,saadat-abad,155,1404.0,3.0,۶ از ۶,بازسازی نشده,35.784826,51.368797,4.0,آسانسور دارد,پارگینگ دارد,انباری دارد
2,77999996928,velenjak,160,1403.0,2.0,۳,بازسازی نشده,35.807008,51.404564,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد
3,2700000000,dolatkhah,57,1398.0,2.0,۴,بازسازی نشده,35.616706,51.342722,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد
4,89999998976,farmaniyeh,215,1397.0,3.0,۲ از ۶,بازسازی نشده,35.796357,51.469127,1.0,آسانسور دارد,پارگینگ دارد,انباری دارد
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4867,27000000512,mirdamad,65,1399.0,1.0,۳,بازسازی نشده,35.762694,51.430621,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد
4868,48000000000,amaniyeh,185,1390.0,3.0,۲,بازسازی نشده,35.788962,51.415925,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد
4869,70000001024,niavaran,259,1388.0,4.0,۶ از ۸,بازسازی نشده,35.811373,51.468525,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد
4870,14499999744,sazman-barname-jonubi,92,1385.0,2.0,۲ از ۵,بازسازی شده,35.729333,51.304251,4.0,آسانسور دارد,پارگینگ دارد,انباری دارد
4871,3500000000,shahr-e-ziba,60,1400.0,2.0,۲,بازسازی نشده,35.746517,51.291940,NaN,آسانسور دارد,پارگینگ دارد,انباری دارد

In [ ]:
df.describe()

,price,metrage,sal,otag,lat,long,tehdad_vahed
count,4.872000e+03,4.872000e+03,4823.000000,4846.000000,4872.000000,4872.000000,2700.000000
mean,1.829965e+11,2.831102e+03,1395.431474,2.004333,35.727559,51.374079,2.094444
std,4.071228e+12,1.413904e+05,8.495090,0.752966,0.040562,0.087658,1.551502
min,1.000000e+03,8.000000e+00,1371.000000,1.000000,35.607664,51.020869,1.000000
25%,5.900000e+09,6.300000e+01,1388.000000,1.000000,35.695214,51.315427,1.000000
50%,1.350000e+10,8.750000e+01,1398.000000,2.000000,35.733053,51.370052,2.000000
75%,2.750000e+10,1.210000e+02,1404.000000,2.000000,35.755656,51.451312,2.000000
max,1.820000e+14,8.815900e+06,1404.000000,4.000000,35.822610,51.602581,8.000000

In [ ]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4872 entries, 0 to 4871
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         4872 non-null   int64
 1   mantage       4872 non-null   str
 2   metrage       4872 non-null   int64
 3   sal           4823 non-null   float64
 4   otag          4846 non-null   float64
 5   tabage        4872 non-null   str
 6   vshed_status  4872 non-null   str
 7   lat           4872 non-null   float64
 8   long          4872 non-null   float64
 9   tehdad_vahed  2700 non-null   float64
 10  asansor       4872 non-null   str
 11  parking       4872 non-null   str
 12  anbari        4872 non-null   str
dtypes: float64(5), int64(2), str(6)
memory usage: 494.9 KB

In [ ]:
df.isnull().sum()

price              0
mantage            0
metrage            0
sal               49
otag              26
tabage             0
vshed_status       0
lat                0
long               0
tehdad_vahed    2172
asansor            0
parking            0
anbari             0
dtype: int64

In [ ]:
df["anbari"].value_counts()

anbari
انباری دارد     4499
انباری ندارد     373
Name: count, dtype: int64

In [ ]:
str_to_o1=["vshed_status","asansor","parking","anbari"]

df["vshed_status"]=df["vshed_status"].replace("بازسازی شده",True)
df["vshed_status"]=df["vshed_status"].replace("بازسازی نشده",False)


df["asansor"]=df["asansor"].replace("آسانسور دارد",True)
df["asansor"]=df["asansor"].replace("آسانسور ندارد",False)


df["parking"]=df["parking"].replace("پارگینگ دارد",False)
df["parking"]=df["parking"].replace("پارگینگ ندارد",False)


df["anbari"]=df["anbari"].replace("انباری دارد",True)
df["anbari"]=df["anbari"].replace("انباری ندارد",False)

In [ ]:
df

,price,mantage,metrage,sal,otag,tabage,vshed_status,lat,long,tehdad_vahed,asansor,parking,anbari
0,1350000000,chitgar-shomali,90,1404.0,2.0,۸ از ۱۵,False,35.724967,51.186593,8.0,True,False,True
1,89999998976,saadat-abad,155,1404.0,3.0,۶ از ۶,False,35.784826,51.368797,4.0,True,False,True
2,77999996928,velenjak,160,1403.0,2.0,۳,False,35.807008,51.404564,NaN,True,False,True
3,2700000000,dolatkhah,57,1398.0,2.0,۴,False,35.616706,51.342722,NaN,True,False,True
4,89999998976,farmaniyeh,215,1397.0,3.0,۲ از ۶,False,35.796357,51.469127,1.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4867,27000000512,mirdamad,65,1399.0,1.0,۳,False,35.762694,51.430621,NaN,True,False,True
4868,48000000000,amaniyeh,185,1390.0,3.0,۲,False,35.788962,51.415925,NaN,True,False,True
4869,70000001024,niavaran,259,1388.0,4.0,۶ از ۸,False,35.811373,51.468525,NaN,True,False,True
4870,14499999744,sazman-barname-jonubi,92,1385.0,2.0,۲ از ۵,True,35.729333,51.304251,4.0,True,False,True
4871,3500000000,shahr-e-ziba,60,1400.0,2.0,۲,False,35.746517,51.291940,NaN,True,False,True

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4872 entries, 0 to 4871
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         4872 non-null   int64
 1   mantage       4872 non-null   str
 2   metrage       4872 non-null   int64
 3   sal           4823 non-null   float64
 4   otag          4846 non-null   float64
 5   tabage        4872 non-null   str
 6   vshed_status  4872 non-null   object
 7   lat           4872 non-null   float64
 8   long          4872 non-null   float64
 9   tehdad_vahed  2700 non-null   float64
 10  asansor       4872 non-null   object
 11  parking       4872 non-null   object
 12  anbari        4872 non-null   object
dtypes: float64(5), int64(2), object(4), str(2)
memory usage: 494.9+ KB

In [ ]:
df["parking"].value_counts()

parking
False    4872
Name: count, dtype: int64